### ISSUE TITLE
Rocky Linux container generates wrong YUM URLs because $basearch is empty

### ISSUE THREAD

**Issue by strzibny** [fullstaq-ruby/server-edition#105]
**Describe the bug**

I wanted to try to build a Rocky Linux 8 base image with fullstaq Ruby package. However, the package was not installed.

**To Reproduce**
Linux distribution: Rocky Linux 8
Package name: fullstaq-ruby-3.0.1-jemalloc
Docker: version 20.10.12, build 485636f

```
FROM rockylinux:8 AS base

RUN echo -e "\
[fullstaq-ruby]\n\
name=fullstaq-ruby\n\
baseurl=https://yum.fullstaqruby.org/centos-8/$basearch\n\
gpgcheck=0\n\
repo_gpgcheck=1\n\
enabled=1\n\
gpgkey=https://raw.githubusercontent.com/fullstaq-labs/fullstaq-ruby-server-edition/main/fullstaq-ruby.asc\n\
sslverify=1\n"\
> /etc/yum.repos.d/fullstaq-ruby.repo

RUN dnf update -y && \
  dnf install -y fullstaq-ruby-3.0.1-jemalloc
```

~~~
Errors during downloading metadata for repository 'fullstaq-ruby':
  - Status code: 404 for https://storage.googleapis.com/fullstaq-ruby-server-edition-yum-repo/versions/11/public/centos-8/repodata/repomd.xml (IP: 142.251.36.112)
Error: Failed to download metadata for repo 'fullstaq-ruby': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

~~~

**Expected behavior**

The said package is installed.

Note that if I just add the repo on my Fedora, I can see the package there for download. Perhaps I am just forgetting something.

**Comment by FooBarWidget** [comment]
The URL after https://storage.googleapis.com/fullstaq-ruby-server-edition-yum-repo/versions/11/public/centos-8 should be "x86_64/repodata/repomd.xml", not "repodata/repomd.xml". It seems that in the Rocky Linux container, $basearch is empty.

So either something's weird in Rocky Linux, or we need to update our installation instructions. Advice from Enterprise Linux experts is appreciated.

**Comment by strzibny** [comment]
Okay, I tried a few things, and it's clear the `$basearch` is not filled. So it's a general issue of the Rocky image.

**Comment by strzibny** [comment]
Okay, so it turns our that while I was changing the file from cat/heredoc to echo I didn't escape `$`. Thanks @voxik for spotting it.

I am sorry for the noise!
