### ISSUE TITLE
Phusion Passenger not running with Fullstaq Ruby

### ISSUE THREAD

**Issue by westonganger** [fullstaq-ruby/server-edition#110]
Trying to use an apt-installed version of fullstaq ruby with Passenger and Nginx on Debian 11 installed via the recommended process from the Passenger website

I am noticing that passenger is booting using the default OS provided Ruby rather than the specific version we install from the Fullstaq repo.

```
App 101885 output: Error: The application encountered the following error: Your Ruby version is 2.7.4, but your Gemfile specified ~> 3.1 (Bundler::RubyVersionMismatch)
```

I have .ruby-version and a ruby version in the Gemfile. Accessing the folder via ssh and running `ruby -v` returns correct ruby version (3.1).

I also found a recent stackoverflow question with exactly the same content I would've asked. https://stackoverflow.com/questions/73720856/phusion-passenger-running-with-fullstaq-ruby

Linux distribution: [Debian 11]
Package name: [fullstaq-ruby-3.1-jemalloc]

**Comment by westonganger** [comment]
Also tracking at [phusion/passenger#2453](https://github.com/phusion/passenger/issues/2453)

**Comment by westonganger** [comment]
Fix is to add the following to the sites nginx config (which is mentioned in the readme)

passenger_ruby /home/<username>/.rbenv/shims/ruby

**Comment by FooBarWidget** [comment]
`passenger_ruby` should work as expected. Maybe there's an issue with PATH that makes Passenger detect the system Ruby instead. If you set `passenger_log_level 7` then you should be able to see in the debug output which Ruby was chosen and what the PATH was.
