### ISSUE TITLE
Can not access https://apt.fullstaqruby.org/ from several IP addresses

### ISSUE THREAD

**Issue by noniq** [fullstaq-ruby/server-edition#113]
**Describe the bug**
On two recently provisioned servers accessing https://apt.fullstaqruby.org/ results in a `403 Forbidden` error. It is thus not possible to add the repository to the apt sources and to install the fullstaq-ruby packages.

On several other servers it works normally, though. Maybe there is some kind of IP based filtering / blacklisting in place?

**To Reproduce**
Linux distribution: Ubuntu 22.04

1. Run command `curl https://apt.fullstaqruby.org/dists/ubuntu-22.04/InRelease`
2. See error:

~~~
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/dists/ubuntu-22.04/InRelease</code> from this server.</h2>
<h2></h2>
</body></html>
~~~

**Expected behavior**

Running the same command on other servers (also Ubuntu 22.04) gives the expected output:

~~~
HTTP/1.1 302 Moved Temporarily
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Content-Length: 146
Content-Type: text/html
Date: Thu, 15 Dec 2022 16:34:12 GMT
Location: https://storage.googleapis.com/fullstaq-ruby-server-edition-apt-repo/versions/18/public/dists/ubuntu-22.04/InRelease
Server: nginx/1.19.10
Via: 1.1 google

<html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.19.10</center>
</body>
</html>
~~~ 

Affected IPs (currently): 65.21.187.103, 157.90.162.60 (both are part of Hetzner Cloud Service in Germany).

**Comment by FooBarWidget** [comment]
Works for me. Could be a temporary issue. Does it work for you now?

**Comment by noniq** [comment]
Unfortunately not, trying to access the URL from 157.90.162.60 still fails (can't test with 65.21.187.103 – we already deprovisioned that particular server). Access from various other IPs from the same hosting company / data center works normally though. 

So this indeed looks like IP-based blocking. I understand that data center IPs are ofent blocked from accessing “normal” websites because they tend to be abused for DDOS attacks and such; but I think this should not be done on “infrastructure” websites like packages repositories. 

We could probably work around this by configuring apt to use a proxy. But what if the proxy’s IP address gets randomly blocked, too?

**Comment by FooBarWidget** [comment]
I didn't configure any IP blocking so if there's any blocking then Google Cloud did that. Unfortunately this is not under my control.

**Comment by kaspergrubbe** [comment]
I assume your access patterns looks a bit odd compared to the regular Google Storage user as some (most?) of the traffic is coming from datacenters.

I am a bit saddened about the response here, you've chosen to use a vendor that blocks legitimate traffic. I am also blocked from using Fullstaq Ruby, I have servers on Hetzner too.

Can we help you look into an alternative hosting provider? 

Or could we contact Google and ask them why they seem to block legitimate traffic, maybe there's a setting to enable/disable?

**Comment by FooBarWidget** [comment]
Google Cloud was provided to me as part of a sponsorship deal so there's not much I can do about this unless someone else provides hosting sponsorship.

I also use Fullstaq Ruby myself on Hetzner servers and I never had any trouble.

You should definitely contact Google Cloud and ask why you're blocked.

I don't think the blocking happens through Cloud Storage, but through Load Balancer.
