### ISSUE TITLE
Ruby 3.2

### ISSUE THREAD

**Issue by ollym** [fullstaq-ruby/server-edition#114]
Add support for newly released Ruby 3.2

**Comment by FooBarWidget** [comment]
Would you like to try contributing this? Instructions here:

 * https://github.com/fullstaq-ruby/server-edition/blob/main/dev-handbook/add-new-ruby-version.md
 * https://github.com/fullstaq-ruby/server-edition/blob/main/dev-handbook/testing-packages-locally.md

**Comment by FooBarWidget** [comment]
Looks like someone else submitted a pull request: #115
