### ISSUE TITLE
Yum repo down (502)

### ISSUE THREAD

**Issue by alexclarkee** [fullstaq-ruby/server-edition#122]
Getting a 502 when trying to hit the yum repo - https://yum.fullstaqruby.org/

On web:
Error: Server Error
The server encountered a temporary error and could not complete your request.
Please try again in 30 seconds.

Using yum:
fullstaq-ruby-3.0.4-malloctrim FAILED
https://yum.fullstaqruby.org/centos-7/x86_64/fullstaq-ruby-3.0.4-malloctrim-rev8-centos7.x86_64.rpm: [Errno 14] HTTPS Error 502 - Bad Gateway

Was working earlier in the day.

**Comment by Xymist** [comment]
Also true of the `apt` repo.

**Comment by wflanagan** [comment]
Hit this problem with apt.

**Comment by neo87cs** [comment]
Contacted the support through their site, they have been notified and are looking into the problem

**Comment by jhirn** [comment]
Is there a mirror or alternative host that can be used. I have some production deploys out of the water atm. 

Thanks!

**Comment by qdegraeve** [comment]
+1 if somebody has a reliable alternative to provide

**Comment by vin01** [comment]
If it helps anyone, a couple of options since it has been down for a long time now:

- Build your own packages using build scripts from this repo, depending on your ruby version and OS requirements, you can use different scripts from this repo like [`build-ruby-deb`](https://github.com/fullstaq-ruby/server-edition/blob/main/build-ruby-deb). Scripts have helpful messages and instructions, not documented though. You will need `docker` to be able to use them.

- If you already have an environment running one of the packages from the repository, you can try to recreate the installation package of that version and use it until a better solution is available, for Debian/Ubuntu you can use [`dpkg-repack`](https://manpages.ubuntu.com/manpages/bionic/man1/dpkg-repack.1.html) to build `.deb` packages.

**Comment by neo87cs** [comment]
if someone is coming here from opsworks_ruby (https://github.com/ajgon/opsworks_ruby) this may help. If you open setup.rb and check for the `ruby-provider` blocks you may add
```
elsif node['ruby-provider'] == 'ruby-build'
  ruby_package_ver = node['ruby-version']
  # custom flow, ruby-ng is not supported no more
  include_recipe 'ruby_build::default'
  ruby_build_ruby "#{ruby_package_ver}"
  # attach refs as previous if block
  path = "/usr/local/ruby/#{ruby_package_ver}/bin:" \
         '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games'
  # injecting in environment
  template '/etc/environment' do
    source 'environment.erb'
    mode 0o664
    owner 'root'
    group 'root'
    variables(environment: { 'PATH' => path })
  end
  # install correct bundler
  execute 'install bundler' do
    command "/usr/local/ruby/#{ruby_package_ver}/bin/gem install bundler -v #{node['bundler-version']}"
    user 'root'
    environment('PATH' => path)
  end
  # relink ruby
  link '/usr/local/bin/bundle' do
    to "/usr/local/ruby/#{ruby_package_ver}/bin/bundle"
  end
  link '/usr/local/bin/ruby' do
    to "/usr/local/ruby/#{ruby_package_ver}/bin/ruby"
  end
```
and add deps inside metadata.rb `depends 'ruby_build'` of opsworks_ruby cookbook, then just enrich your cookbook project with the correct ruby_build cookbook version.

**Comment by jhirn** [comment]
Ops works ruby... oh uh.. no, not me... (how did you know????)

**Comment by jhirn** [comment]
Can you approximate how long it will take to get the mirrors up. Will my opsworks cookbooks still require an update as @neo87cs suggested or will the original URI resolve once the mirror is up?

**Comment by qdegraeve** [comment]
@neo87cs thank you for the tip. I did not yet manage to make it work. What version of the `ruby-build` cookbook did you take ?

**Comment by neo87cs** [comment]
> @neo87cs thank you for the tip. I did not yet manage to make it work. What version of the `ruby-build` cookbook did you take ?

ruby-build -> `1.1.0`
yum-epel -> `4.1.3`
git -> `9.0.1`

Be sure to download the right versions from git repos (supermarket let you download always the last one)

**Comment by qdegraeve** [comment]
Thanks for your reply. I did make it work with `ruby-build` version `1.3.0` and `git` version `10.1` as I start by updating chef version to `15` in the setup script. For now everything works but I still have to do some more tests I have something like 100 servers running on opsworks stacks.
Thanks a lot for your help, I really appreciate that. I think this episode will force us to accelerate on finding other options than old and deprecated opsworks stacks.

**Comment by neo87cs** [comment]
> Thanks for your reply. I did make it work with `ruby-build` version `1.3.0` and `git` version `10.1` as I start by updating chef version to `15` in the setup script. For now everything works but I still have to do some more tests I have something like 100 servers running on opsworks stacks. Thanks a lot for your help, I really appreciate that. I think this episode will force us to accelerate on finding other options than old and deprecated opsworks stacks.

indeed, aws definitely forgot opsworks :(, i hope at least fullstaq will come back as i love their repos

**Comment by bogn83** [comment]
> Can you approximate how long it will take to get the mirrors up. Will my opsworks cookbooks still require an update as @neo87cs suggested or will the original URI resolve once the mirror is up?

@jhirn the mirror will not be public as I wrote, so sadly for the moment we can't help out here. I was just giving it as an inspiration/idea.

**Comment by saiqulhaq-hh** [comment]
Another idea is to change the base image to https://github.com/evilmartians/fullstaq-ruby-docker

**Comment by Ranger-X** [comment]
It seems the APT repository is up :+1:

**Comment by neo87cs** [comment]
> Another idea is to change the base image to https://github.com/evilmartians/fullstaq-ruby-docker

is it possibile to let opsworks run it correctly? It could be very awesome, we are thinking to migrate our opsworks to ecs

**Comment by FooBarWidget** [comment]
It's fixed now.
