### ISSUE TITLE
Debian 12 `bookworm` support

### ISSUE THREAD

**Issue by ducthien1490** [fullstaq-ruby/server-edition#124]
**Is your feature request related to a problem? Please describe.**
Debian 12 released recently (https://www.debian.org/News/2023/20230610), bringing many support and fixing many vulnerabilities from Debian 11.

**Describe the solution you'd like**
New version to support Debian 12 `bookworm`

**Comment by FooBarWidget** [comment]
Rolling out right now.

**Comment by FooBarWidget** [comment]
The announcement: https://github.com/fullstaq-ruby/server-edition/discussions/126

**Comment by ducthien1490** [comment]
Thanks @FooBarWidget
