### ISSUE TITLE
Could not install fullstaq-ruby anymore on Ubuntu 18.04

### ISSUE THREAD

**Issue by qdegraeve** [fullstaq-ruby/server-edition#128]
**Describe the bug**
Hi, from today I cannot install any ruby version on ubuntu 18.04 because of below error.
It may be related to the drop of support for ubuntu 18.04 but I think the apt repo should remain accessible.
I think there is a probleme on where apt search for the release file, in `https://storage.googleapis.com/fullstaq-ruby-server-edition-apt-repo/versions/22/public` while it should be `https://storage.googleapis.com/fullstaq-ruby-server-edition-apt-repo/versions/18/public`

Is there any chance I still be able to install ruby on Ubuntu 18.04 , at least during a certain amount of time so that I have time to change my infrastructure (~ 100 servers) ?

**To Reproduce**
Linux distribution: Ubuntu 18.04
Package name: any package

~~~
---- Begin output of ["apt-get", "-q", "update"] ----
STDOUT: Hit:1 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease
Ign:5 https://storage.googleapis.com/fullstaq-ruby-server-edition-apt-repo/versions/22/public ubuntu-18.04 InRelease
Err:6 https://storage.googleapis.com/fullstaq-ruby-server-edition-apt-repo/versions/22/public ubuntu-18.04 Release
404  Not Found [IP: 74.125.193.128 443]
Reading package lists...
STDERR: E: The repository 'https://apt.fullstaqruby.org ubuntu-18.04 Release' does not have a Release file.
~~~

**Comment by FooBarWidget** [comment]
I will look into this issue but in the mean time you can use https://storage.googleapis.com/fullstaq-ruby-server-edition-apt-repo/versions/18/public instead of https://apt.fullstaqruby.org as your APT source.

**Comment by FooBarWidget** [comment]
I will look into this issue but in the mean time you can use https://storage.googleapis.com/fullstaq-ruby-server-edition-apt-repo/versions/21/public (not 18) instead of https://apt.fullstaqruby.org/ as your APT source.

**Comment by qdegraeve** [comment]
Thank you so much for the tips @FooBarWidget . You saved my day 😍

**Comment by FooBarWidget** [comment]
Rolling out a fix.

**Comment by FooBarWidget** [comment]
Does it work now?

**Comment by dotnofoolin** [comment]
I'm seeing the same errors that @qdegraeve posted above.

**Comment by FooBarWidget** [comment]
Updated fix is being rolled out (takes ~1h). Let me know whether it works.

**Comment by jec** [comment]
I'm still getting an error with that repo:

```
execute[apt-get -q update] (/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/provider/apt_update.rb line 80) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
---- Begin output of apt-get -q update ----
STDOUT: Hit:1 http://us-east-2.ec2.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://us-east-2.ec2.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://us-east-2.ec2.archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:5 https://download.newrelic.com/infrastructure_agent/linux/apt bionic InRelease
Hit:6 https://deb.nodesource.com/node_16.x bionic InRelease
Hit:7 https://dl.yarnpkg.com/debian stable InRelease
Ign:8 https://storage.googleapis.com/fullstaq-ruby-server-edition-apt-repo/versions/24/public ubuntu-18.04 InRelease
Err:9 https://storage.googleapis.com/fullstaq-ruby-server-edition-apt-repo/versions/24/public ubuntu-18.04 Release
404  Not Found [IP: 142.250.190.144 443]
Reading package lists...
STDERR: E: The repository 'https://apt.fullstaqruby.org ubuntu-18.04 Release' does not have a Release file.
---- End output of apt-get -q update ----
Ran apt-get -q update returned 100
```

**Comment by vallyre** [comment]
Hi @FooBarWidget .... any ideas to help remediate this?  We're seeing this as well and it's quite a blocker...

**Comment by FooBarWidget** [comment]
I'm working on a fix. In the mean time you can do this https://github.com/fullstaq-ruby/server-edition/issues/128#issuecomment-1621459629

**Comment by vallyre** [comment]
Hi @FooBarWidget , we cannot incorporate this workaround, as it's AWS's Chef pipeline which is pulling in this particular package that does not exist.  We cannot change Chef's choice, other than the ruby-provider ('fullstaq'), ruby-variant ('jemalloc') and ruby-version ('2.7').  Any ideas?

**Comment by FooBarWidget** [comment]
If this latest fix works then it'll be live in an hour.

**Comment by FooBarWidget** [comment]
It should be fixed for real this time. It works in my test.

**Comment by vallyre** [comment]
You betcha!  It works for us as well!  Thank you!!!
