### ISSUE TITLE
Release file for Ubuntu 24.04 not found

### ISSUE THREAD

**Issue by G-Rath** [fullstaq-ruby/server-edition#146]
**Describe the bug**
When trying to upgrade to Ubuntu 24.04, `apt` claims the release file does not exist for fullstaq-ruby

**To Reproduce**
Linux distribution: Ubuntu 24.04
Package name: any

1. Run through the install steps in the readme
2. See error:

~~~
root@staging-app-i-123abc:/home/deploy# apt update
Hit:1 http://ap-southeast-2.ec2.archive.ubuntu.com/ubuntu noble InRelease
Hit:2 http://ap-southeast-2.ec2.archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:3 http://ap-southeast-2.ec2.archive.ubuntu.com/ubuntu noble-backports InRelease
Hit:4 https://deb.nodesource.com/node_18.x nodistro InRelease
Hit:6 http://security.ubuntu.com/ubuntu noble-security InRelease
Ign:5 https://storage.googleapis.com/fullstaq-ruby-server-edition-apt-repo/versions/27/public ubuntu-24.04 InRelease
Err:7 https://storage.googleapis.com/fullstaq-ruby-server-edition-apt-repo/versions/27/public ubuntu-24.04 Release
  404  Not Found [IP: 172.217.167.91 443]
Reading package lists... Done
E: The repository 'https://apt.fullstaqruby.org ubuntu-24.04 Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
~~~

**Expected behavior**
The command to be successful and that I can install Ruby using fullstaq on Ubuntu 24.04

**Additional logs**
If applicable, add additional logs to help explain your problem.

~~~
root@staging-app-i-123abc:/home/deploy# cat /etc/apt/sources.list.d/fullstaq-ruby.list
deb https://apt.fullstaqruby.org ubuntu-24.04 main
~~~

**Comment by G-Rath** [comment]
@joesiewert has [also reported this](https://github.com/fullstaq-ruby/server-edition/pull/142#issuecomment-2207266741) on #142

**Comment by G-Rath** [comment]
Ah I'm guessing it's because https://github.com/fullstaq-ruby/server-edition/actions/runs/9513799335 has failed - @FooBarWidget any chance you could rerun that workflow?

**Comment by FooBarWidget** [comment]
Ah yes I didn't notice that it failed. Looks like a network timeout. I'll rerun it.

**Comment by FooBarWidget** [comment]
The CI is running into trouble again: publishing fails because the CI runner runs out of disk space. I'll have to find a solution for this...

**Comment by FooBarWidget** [comment]
Should be fixed now.

**Comment by G-Rath** [comment]
Awesome thanks @FooBarWidget, it looks to be working now, though it does look like only the latest patch/tiny version of each major.minor of Ruby is available.

Is that intentional or related to the CI failure? not a huge blocker, but just means we've got a bit more faff to get through before we can upgrade so if it is a bug that'd be great to have resolved.

**Comment by FooBarWidget** [comment]
This is intentional. When a new distribution is added, we only add the latest tiny versions.
