### ISSUE TITLE
apt.fullstaqruby.org is down

### ISSUE THREAD

**Issue by seabre** [fullstaq-ruby/server-edition#148]
**Describe the bug**
apt.fullstaqruby.org is not up, so cannot access the apt repository.

**To Reproduce**

In your web browser, in the URL bar, enter: `https://apt.fullstaqruby.org`, then press enter.

You see "This site can’t be reached" when done loading.

**Expected behavior**

Should see a directory listing of packages.

**Comment by FooBarWidget** [comment]
I migrated to a different DNS server but forgot to update DNSSEC. This should be solved now (or you need to wait for your DNS server's caches to expire).

**Comment by seabre** [comment]
I'm going to open a separate issue later, but heads up that builds aren't working either, unless I'm doing something wrong:

<img width="1161" alt="image" src="https://github.com/user-attachments/assets/44bb674a-7a09-4b7f-96fd-d887ac985b02">

**Comment by FooBarWidget** [comment]
*That* is fixed now.
