### ISSUE TITLE
apt.fullstaqruby.org is down again

### ISSUE THREAD

**Issue by seabre** [fullstaq-ruby/server-edition#154]
Describe the bug
apt.fullstaqruby.org is not up, so cannot access the apt repository. Previously reported as #148.

To Reproduce

In your web browser, in the URL bar, enter: https://apt.fullstaqruby.org, then press enter.

You see:
```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: fsruby-server-edition-apt-repo/versions/32/public/</Details>
</Error>
```
in the body and `https://storage.googleapis.com/fsruby-server-edition-apt-repo/versions/32/public/` in the URL bar (assuming a direct or something) when done loading.

Expected behavior

Should see a directory listing of packages.

**Comment by FooBarWidget** [comment]
I'll have a look.

**Comment by FooBarWidget** [comment]
The repository is not down. It works if you use 'apt install'. Going to https://apt.fullstaqruby.org is not supposed to give a file listing. Google Cloud Storage expects an exact object key. For example if you go to https://apt.fullstaqruby.org/dists/ubuntu-24.04/Release then it works.
